// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9uK0uhcuRivEKgvbD6BVNZ3q5wljB9A',
    appId: '1:59681281539:web:85c23a4a14514711ada036',
    messagingSenderId: '59681281539',
    projectId: 'ayuveer-76768',
    authDomain: 'ayuveer-76768.firebaseapp.com',
    storageBucket: 'ayuveer-76768.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1l8OjybVNiwwAL6SWqRXCX1fWLj96rio',
    appId: '1:59681281539:android:f5066ead8233fe4dada036',
    messagingSenderId: '59681281539',
    projectId: 'ayuveer-76768',
    storageBucket: 'ayuveer-76768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUAbjM6tlyLeFTsxtonQU0eXOmeAOdRk',
    appId: '1:59681281539:ios:0dda81879444bac5ada036',
    messagingSenderId: '59681281539',
    projectId: 'ayuveer-76768',
    storageBucket: 'ayuveer-76768.appspot.com',
    iosBundleId: 'com.example.ayuveerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqUAbjM6tlyLeFTsxtonQU0eXOmeAOdRk',
    appId: '1:59681281539:ios:0dda81879444bac5ada036',
    messagingSenderId: '59681281539',
    projectId: 'ayuveer-76768',
    storageBucket: 'ayuveer-76768.appspot.com',
    iosBundleId: 'com.example.ayuveerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR9uK0uhcuRivEKgvbD6BVNZ3q5wljB9A',
    appId: '1:59681281539:web:afa616e818716c7cada036',
    messagingSenderId: '59681281539',
    projectId: 'ayuveer-76768',
    authDomain: 'ayuveer-76768.firebaseapp.com',
    storageBucket: 'ayuveer-76768.appspot.com',
  );
}
